### ISSUE TITLE
Tassellation Crash [1.18.1]

### ISSUE THREAD

**Issue by Alexthw46** [Chisel-Team/ConnectedTexturesMod#179] opened 2022-03-30 19:14 UTC
I'm not sure if this belongs here or in Glassentials, but sometimes (not always) when i load another player base i crash with this error.
Every time it seems to be about Glassentials's Ethereal Glass.

Modpack: Ars Nouveau Discord Server (latest 1.18.1)

[crash-2022-03-30_21.01.59-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/8383418/crash-2022-03-30_21.01.59-client.txt)

https://pastebin.com/VscnC6jU

**Comment by justliliandev** [comment] 2022-03-30 19:16
This belongs here and is a duplicate of https://github.com/Chisel-Team/ConnectedTexturesMod/issues/174

**Comment by tterrag1098** [comment] 2022-05-03 15:57
Duplicate of #174

**Closed as completed by tterrag1098** 2022-05-03 15:57 UTC
Labels: duplicate
