### ISSUE TITLE
Mod Crashes with New 1.18.2 Forge Update(

### ISSUE THREAD

**Issue by ModernGamingWorld** [Chisel-Team/ConnectedTexturesMod#184] opened 2022-06-06 05:12 UTC
[crash-2022-06-06_00.03.08-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/8841996/crash-2022-06-06_00.03.08-client.txt)

**Comment by ProsperCraft** [comment] 2022-06-06 06:14
Same
https://gist.github.com/ProsperCraft/3ae97c0ff6f00d194edde708a64a2855

**Comment by Peca21** [comment] 2022-06-06 12:55
.41 forge works fine, .44 crashes, I can't test 42 and 43 since curseforge doesn't have these versions.
But it looks like the problem is in 43

https://github.com/MinecraftForge/MinecraftForge/commit/194f11069fb7c9fcb5dda1f9a517aa31161948eb
https://github.com/MinecraftForge/MinecraftForge/pull/8476
https://github.com/MinecraftForge/MinecraftForge/pull/8664

**Comment by Terminal-Access** [comment] 2022-06-06 16:09
Can Confirm (same crash log's as above)

I believe this crash is a direct result of the change made in forge version ".43", when comparing the Stack trace report to the change log.

**Forge Change Log**
> ~ snip
>  - 40.1.43 [1.18] Avoid exclusive synchronisation in block render type lookups (#8476)
>  ~snip

Again can confirm Peca21's report that when using versions below Forge ".43" there is no crash however as soon as you use any version higher (".44" being the next version publicaly valiable after ".43") the crash occures.  
I have tested forge versions from ".31" right up to ".47"

**Comment by LilJagty** [comment] 2022-06-10 17:46
Still crashing in Forge .51
[crash-2022-06-10_13.42.52-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/8881032/crash-2022-06-10_13.42.52-client.txt)

**Comment by justliliandev** [comment] 2022-06-10 18:08
It should work once https://github.com/MinecraftForge/MinecraftForge/pull/8671 is merged.

**Comment by tterrag1098** [comment] 2022-06-10 18:17
Forge is planning to revert this change. Until then, use version 40.1.42.

**Comment by tterrag1098** [comment] 2022-08-14 02:21
This is long since fixed.

**Closed as completed by tterrag1098** 2022-08-14 02:21 UTC
