### ISSUE TITLE
Solid Color Textures for Chiseled Blocks

### ISSUE THREAD

**Issue by LiteWolf101** [Chisel-Team/ConnectedTexturesMod#9] opened 2017-06-21 14:15 UTC
![chiselissue](https://user-images.githubusercontent.com/23690196/27388737-f8d357cc-5661-11e7-9ef0-80d74c156442.png)

Ran into this issue with Chisel 1.11. Is there a way to solve this issue or should I wait for a new update of Chisel?

**Comment by tterrag1098** [comment] 2017-06-21 18:17
Does this occur without the resourcepack you have?

**Comment by Drullkus** [comment] 2017-06-21 19:39
Is the resource pack on curseforge? If so, could link us to it?

**Comment by Farsinuce** [comment] 2017-08-30 22:06
@tterrag1098 @Drullkus 
I am experiencing the same thing in one client, but not in another.

Using no resource pack.

MC 1.12
Forge 1.12-14.21.1.2443
Mods: https://pastebin.com/8pzezirX

**Comment by P3rf3ctXZer0** [comment] 2018-01-18 18:20
I experienced this bug off and on but mainly after re-logging into the dedicated sever. I think for now I am removing chisel which make me said because I love this mod. 

CTM-MC1.12-0.2.3.12.jar
Unlimited Chisel Works 0.1.9
Chisel - MC1.12-0.1.1.26
Forge 1.12.2 - 14.23.1.2590

![2018-01-18 12_09_02-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/35114261-fda5e1c0-fc38-11e7-9633-0e046465df4f.png)

Fun fact we have almost no mods in common. 

https://github.com/asiekierka/UnlimitedChiselWorks/issues/9

**Comment by P3rf3ctXZer0** [comment] 2018-01-18 18:44
The Xs are the mods not in my modpack - FYI @Drullkus I don't have extact any, I have different versions of the same mods.
https://pastebin.com/6ZiH65xw

**Comment by P3rf3ctXZer0** [comment] 2018-01-18 18:55
I have solved the problem for me at least - remove connected textures from server. Only have it on client good luck solving your issue.

Oi @tterrag1098 add a warning CTM is clientside only!

**Comment by tterrag1098** [comment] 2018-01-18 19:56
CTM does nothing on a server...that fixing your issue was pure coincidence, likely it was fixed just by you restarting your game. My only guess for this issue is that the texture atlas is getting too full, and bugs out. I can't suggest any fix because no one has yet been able to give me a consistent way to reproduce this bug.

**Comment by P3rf3ctXZer0** [comment] 2018-01-18 20:58
Listen I am no fool I am aware its not supposed to do anything on the server but it had an affect. I am not sure exactly what kind of affect as I don't code. Since I only removed that one mod and then everything works as intended is not a "Coincidence" and I did restart the server over 8 times before I realized CTM is a clientside only mod. Don't take my reports lightly >_> I spend a lot of time before wasting my breath.

**Comment by Drullkus** [comment] 2018-01-19 06:14
How much RAM do you have

**Comment by P3rf3ctXZer0** [comment] 2018-01-19 15:30
I have 16GB

**Comment by Drullkus** [comment] 2018-01-19 19:33
How much are you allocating to MC when you launch

**Comment by P3rf3ctXZer0** [comment] 2018-01-19 23:18
6GB

**Comment by P3rf3ctXZer0** [comment] 2018-01-24 00:07
https://github.com/P3rf3ctXZer0/MC-1.12.2-TGGRS/issues/11

**Comment by Drullkus** [comment] 2018-01-24 20:41
Give us the client log when this occurs again.

**Comment by P3rf3ctXZer0** [comment] 2018-01-24 22:50
It may help but even using glitched blocks in Architectures work bench seems to restore the textures. Architectures work bench can be found here.

https://minecraft.curseforge.com/projects/architecturecraft-elytradev?gameCategorySlug=mc-mods&projectID=277631

I was shocked it actually restored the texture of the block used as seen with chisel stairs blocks. This screenshot was take when all textures went missing. (It did not globally restore textures only the single block used.)
![2018-01-23 18_55_05-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/35361353-f233b1f0-0115-11e8-979f-be97308086bf.png)

**Comment by tterrag1098** [comment] 2018-01-25 05:53
Allocated memory hardly matters - this could be a case of running out of VRAM. I've never seen an issue like this one and I have no idea how it could occur. Any kind of log would be helpful but you have yet to provide one.

**Comment by P3rf3ctXZer0** [comment] 2018-01-25 17:11
Okay I will provide one next time it occurs I assure you. Again the bug is so random it seems to take hours to produce I cannot figure out why or when it occurs. Please give me time I will nail it. My server has been up all night without a restart I will check to see if the bug has occurred.

**Comment by P3rf3ctXZer0** [comment] 2018-01-25 17:25
This issue was moved to P3rf3ctXZer0/MC-1.12.2-TGGRS#12

**Comment by P3rf3ctXZer0** [comment] 2018-01-25 17:27
Just close this for now as I cannot reproduce it either and I no longer want to be pressured I have forked the issue for archival purposes.

**Comment by P3rf3ctXZer0** [comment] 2018-01-26 01:36
Server Logs Zip
[logs.zip](https://github.com/Chisel-Team/ConnectedTexturesMod/files/1666287/logs.zip)
All the logs when the server glitch occurred

Client Logs Zip
[logs-client.zip](https://github.com/Chisel-Team/ConnectedTexturesMod/files/1666293/logs-client.zip)

@tterrag1098 @Drullkus

**Comment by tterrag1098** [comment] 2018-01-26 04:01
Try without "TexFix" ?

**Comment by Speiger** [comment] 2018-01-28 22:42
@tterrag1098 well if he runs out of VRam TexFix wouldn't cause it because it has a autoreloading system included so as soon you try to extract the TextureData it gets automatically generated. So i am really interested what causes that. It almost looks like the Compat Issue between, Tinkers & FoamFixAnarchy & TexFix. (if one of these mods is missing or a config in FoamFix is disabled that bug is gone)

**Comment by P3rf3ctXZer0** [comment] 2018-10-25 05:06
Thanks for mocking me. I guess I am done caring about your mod. It is not worth my stress or time.

**Comment by Speiger** [comment] 2018-10-25 19:01
@P3rf3ctXZer0 you mean me? If thats the case. Sry it wasn't intentional.

**Comment by tterrag1098** [comment] 2019-07-29 05:13
Until someone can provide a reliable repro case, this is virtually unfixable as I have zero insight as to the cause.

**Closed as completed by tterrag1098** 2019-07-29 05:13 UTC
Labels: bug, can't reproduce

**Comment by P3rf3ctXZer0** [comment] 2019-07-29 05:15
@tterrag1098 I can safely say in my issue it was with @thutmose 's mod Thutcore he could probably shed light on it better than I can.
