### ISSUE TITLE
CTM/ATM7 0.3.19 Tesselating block model crash

### ISSUE THREAD

**Issue by Mitchell5200** [Chisel-Team/ConnectedTexturesMod#182] opened 2022-05-03 04:01 UTC
Note: I am posting this to both the CTM Github and the ATM7 Github to ensure both teams are aware.
I am getting repeatable crashes while attempting to join my self server for tesselating block model, the affected blocks are from a wide variety of mods but all use connecting textures, like the illuminant panel from Simply Light, or any of the connecting wood planks from Chipped. Removal of CTM fixes the issue, so i assume the root of the problem is there, however sometimes i was able to connect to my server world just fine so the issue is sometimes intermittent.
Four of my most recent logs are provided, but they all appear to be similar in regards to their stacktrace
Edit: CTM version CTM-1.18.2-1.1.4+4

[crash-2022-05-03_10.45.59-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/8608195/crash-2022-05-03_10.45.59-client.txt)
[crash-2022-05-03_10.50.17-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/8608196/crash-2022-05-03_10.50.17-client.txt)
[crash-2022-05-03_10.54.19-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/8608197/crash-2022-05-03_10.54.19-client.txt)
[crash-2022-05-03_10.58.57-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/8608198/crash-2022-05-03_10.58.57-client.txt)

**Comment by tterrag1098** [comment] 2022-05-03 15:53
Duplicate of #174

**Closed as completed by tterrag1098** 2022-05-03 15:53 UTC
Labels: duplicate
