### ISSUE TITLE
Three-way bug between CTM, Modern Warfare, and Immersive Engineering

### ISSUE THREAD

**Issue by Mattrock607** [Chisel-Team/ConnectedTexturesMod#58] opened 2018-04-21 00:30 UTC
A trifecta bug! Yay!

If you install CTM, Immersive Engineering, and Vic's Modern Warfare in 1.12.2, a strange bug occurs where the textures on IE scaffolding are messed up and filled with black and purple blobs. Removing either CTM or Vic's Modern Warfare will alleviate the issue, but all three mods cannot be run together without this bug occurring. Which is a real bummer, because I'd really love to include Chisel, IE, and Modern Warfare in my modpack and on my server! :(

The mod versions that matter:

CTM-MC1.12-0.2.3.12)
mw-1.11.6_mc1.12.2
ImmersiveEngineering-0.12-80

Technic modpack where we found the bug: Waywardcraft 1.12.2 edition 

(I removed Modern Warfare from the pack to make it functional; half of the buildings in our world are made from chisel so we can't lose it)

**Comment by VioletWyvern** [comment] 2018-05-15 03:37
Same problem here,  Tested in some mods and some connect textures was showing as purple missing textures

<a href="https://imgur.com/xP7dXJr"><img src="https://i.imgur.com/xP7dXJr.png" title="source: imgur.com" /></a>

Tested mods (will have missing texture):

ImmersiveEngineering
Mekanism
TwilightForest
Techguns
Vic's Modern Warfare

**Comment by tterrag1098** [comment] 2018-06-03 16:40
I believe this is a duplicate of #54, please try the latest release (0.3.0)

**Closed as completed by tterrag1098** 2018-06-03 16:40 UTC
