### ISSUE TITLE
CTM Biome Dependent.

### ISSUE THREAD

**Issue by DnatorGames** [Chisel-Team/ConnectedTexturesMod#17] opened 2017-07-30 06:52 UTC
It would be awesome if there was an option for textures to recognize one biome from another. 

Such as adding seashells to sand while on beaches, and skulls to sand in the desert. :)

**Comment by Drullkus** [comment] 2017-07-30 06:54
Duplicate of #1. 

Yes, this'd be interesting to have! I'm thinking this should be implemented on the model end, to avoid getting messy with the Rendertype system.

**Closed as completed by Drullkus** 2017-07-30 06:54 UTC
