### ISSUE TITLE
[Crash] Literally can't play Minecraft 1.18.2

### ISSUE THREAD

**Issue by A5TC** [Chisel-Team/ConnectedTexturesMod#185] opened 2022-06-13 02:32 UTC
[latest.log](https://github.com/Chisel-Team/ConnectedTexturesMod/files/8887472/latest.log)
[crash-2022-06-12_20.06.27-client.txt](https://github.com/Chisel-Team/ConnectedTexturesMod/files/8887476/crash-2022-06-12_20.06.27-client.txt)

I have 320+ mods, this outdated mod is making it impossible to load a SP world. I have had to force close Minecraft every time I tried to play any of my SP worlds, even brand new SP worlds fail to load at all.

**Comment by Royal-Jelly** [comment] 2022-06-13 03:05
I can also confirm with my private pack seemingly anything after forge 40.1.25 crashes with CTM installed

**Comment by Royal-Jelly** [comment] 2022-06-13 03:07
Duplicate of #184

**Comment by ghost** [comment] 2022-06-30 17:48
Fixed with forge release 40.1.54.

**Closed as completed** 2022-08-14 02:21 UTC
